#!/bin/bash
#=====================================================================
# Internatioinal SQL-Ledger-Network Association
#
#  Author: Sebastian Weitmann
#     Web: http://www.sql-ledger-network.com
#   Email: info@sql-ledger-network.com
#
#======================================================================
#
# Installation Script for SQL-Ledger Run my Accounts Community Version
#
# for Debian 8.6 (Jessie)
#
#======================================================================
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details:
# <http://www.gnu.org/licenses/>.
#======================================================================
#
#This script calls the installation function
#
#

# Main installation routine

installation ()
{

clear
echo "Installing SQL-Ledger Network Community Versions..."

sleep 4
cd ~/
apt-get install debian-archive-keyring

apt-key update
apt-get update
apt-get upgrade

apt-get -y install acpid apache2 openssl ssl-cert postgresql git-core
apt-get -y install gitweb postfix mailutils texlive lynx make cpan apg
apt-get -y install libdbix-simple-perl libdbi-perl libdbd-pg-perl
apt-get -y install libmime-lite-perl libmime-tools-perl libgd2-xpm-dev
apt-get -y install libcgi-formbuilder-perl libnumber-format-perl
apt-get -y install libtext-markdown-perl libdate-calc-perl libdatetime-perl
apt-get -y install libtext-markdown-perl libobject-signature-perl
apt-get -y install libtemplate-perl libhtml-template-perl
apt-get -y install libnumber-format-perl libtemplate-plugin-number-format-perl
apt-get -y install libgd-gd2-perl libhtml-format-perl
apt-get -y install build-essential libuser-simple-perl
apt-get -y install libxml-simple-perl libcgi-simple-perl

apt-get -y install ncftp nano denyhosts harden harden-doc harden-servers checksecurity

apt-get -y install perl libnet-ssleay-perl libauthen-pam-perl libpam-runtime libio-pty-perl apt-show-versions python
wget http://prdownloads.sourceforge.net/webadmin/webmin_1.820_all.deb
dpkg --install webmin_1.820_all.deb


cpan CGI::FormBuilder DBIx::XHTML_Table
cpan GD
cpan GD::Thumbnail
cpan cpan MIME::Lite::TT::HTML

a2ensite default-ssl
service apache2 reload
a2enmod ssl
a2enmod cgi
service apache2 restart

cd /var/www/html
git clone https://github.com/sweitmann/rma-community-version.git sql-ledger
git clone https://github.com/ledger123/runmyaccounts.git rma
git clone https://github.com/ledger123/ledger123.git ledger123

cd /var/www/html/sql-ledger
mkdir spool
cp sql-ledger.conf.default sql-ledger.conf
cd /
wget http://www.sql-ledger-network.com/debian/demousers.tar.gz --retr-symlinks=no
tar -xvf demousers.tar.gz
mv /var/www/html/ledger123/users /var/www/html/sql-ledger
cd /var/www/html/sql-ledger
chown -hR www-data.www-data users templates css spool


cd /var/www/html/ledger123
git clone git://github.com/ledger123/ledgercart.git ledgercart
cp sql-ledger.conf.default sql-ledger.conf
mkdir spool
mkdir /var/www/html/ledger123/users
cd /var/www/html/ledger123/users
wget http://www.sql-ledger-network.com/debian/demo_users.tar.gz --retr-symlinks=no
tar -xvf demo_users.tar.gz
cd /var/www/htlm/ledger123
wget http://www.sql-ledger-network.com/debian/demo_templates.tar.gz --retr-symlinks=no
tar -xvf demo_templates.tar.gz
git checkout -b rel3 origin/rel3
git checkout rel3
chown -hR www-data.www-data users templates css spool

cd /var/www/html/rma
mkdir spool
cp sql-ledger.conf.default sql-ledger.conf
chown -hR www-data.www-data users templates css spool

cd ~/
wget http://www.sql-ledger-network.com/debian/sl_index.html --retr-symlinks=no
mv sl_index.html /var/www/html/index.html

wget http://www.sql-ledger-network.com/debian/sql-ledger --retr-symlinks=no
cp sql-ledger /etc/apache2/sites-available/sql-ledger.conf
cd /etc/apache2/sites-enabled/
ln -s ../sites-available/sql-ledger 001-sql-ledger

echo "AddHandler cgi-script .pl" >> /etc/apache2/apache2.conf
echo "Alias /ledger123 /var/www/html/ledger123" >> /etc/apache2/apache2.conf
echo "<Directory /var/www/html/ledger123>" >> /etc/apache2/apache2.conf
echo "Options ExecCGI Includes FollowSymlinks" >> /etc/apache2/apache2.conf
echo "</Directory>" >> /etc/apache2/apache2.conf
echo "<Directory /var/www/html/ledger123/users>" >> /etc/apache2/apache2.conf
echo "Order Deny,Allow" >> /etc/apache2/apache2.conf
echo "Deny from All" >> /etc/apache2/apache2.conf
echo "</Directory>" >> /etc/apache2/apache2.conf

echo "<Directory /var/www/html/sql-ledger>" >> /etc/apache2/apache2.conf
echo "Options ExecCGI Includes FollowSymlinks" >> /etc/apache2/apache2.conf
echo "</Directory>" >> /etc/apache2/apache2.conf
echo "<Directory /var/www/html/sql-ledger/users>" >> /etc/apache2/apache2.conf
echo "Order Deny,Allow" >> /etc/apache2/apache2.conf
echo "Deny from All" >> /etc/apache2/apache2.conf
echo "</Directory>" >> /etc/apache2/apache2.conf

echo "<Directory /var/www/html/rma>" >> /etc/apache2/apache2.conf
echo "Options ExecCGI Includes FollowSymlinks" >> /etc/apache2/apache2.conf
echo "</Directory>" >> /etc/apache2/apache2.conf
echo "<Directory /var/www/html/rma/users>" >> /etc/apache2/apache2.conf
echo "Order Deny,Allow" >> /etc/apache2/apache2.conf
echo "Deny from All" >> /etc/apache2/apache2.conf
echo "</Directory>" >> /etc/apache2/apache2.conf

service apache2 restart
cd ~/

wget http://www.sql-ledger-network.com/debian/pg_hba.conf --retr-symlinks=no
cp pg_hba.conf /etc/postgresql/9.4/main/
service postgresql restart
su postgres -c "createuser -d -S -R sql-ledger"
su postgres -c "createdb ledgercart"
su postgres -c "psql ledgercart < /var/www/html/ledger123/ledgercart/sql/ledgercart.sql"
su postgres -c "psql ledgercart < /var/www/html/ledger123/ledgercart/sql/schema.sql"
su postgres -c "psql -U postgres ledgercart < /var/www/html/ledger123/sql/Pg-custom_tables.sql"
cp /var/www/html/ledger123/ledgercart/config-default.pl /var/www/html/ledger123/ledgercart/config.pl

wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
tar xf install-tl-unx.tar.gz
cd install-tl-20161103
./install-tl
tex --version

}

# Main program

clear

echo "International SQL-Ledger Network Association"
echo "This is free software, and you are welcome to redistribute it under"
echo "certain conditions; See <http://www.gnu.org/licenses/> for more details"
echo "This script will install SQL-Ledger and LedgerCart on Linux Debian Jessie." 
echo "This program comes with ABSOLUTELY NO WARRANTY"
echo ""
echo ""
echo "If you want to install Run my Accounts Community Version"
echo "please type 'SQL-Ledger-Network' and press <Enter>"
echo ""
read input

if [ "$input" = "SQL-Ledger-Network" ]; then
installation
clear
echo ""
echo "The installation has now been completed."
echo ""
echo "Login to Run my Accounts Community Version with user 'admin' on"
echo "http://yourserver_ip"
echo ""
echo "And your server IP is:"
echo `ifconfig eth0 2>/dev/null|awk '/inet addr:/ {print $2}'|sed 's/addr://'`
echo ""
echo "Visit http://forum.sql-ledger-network.com for support"
echo ""
echo ""
echo "IMPORTANT NOTE: This simple installation was only designed to run on your"
echo "local network."
fi
exit 0

